# -*- coding: utf-8 -*-
"""Component4_Fixed_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmmY8fLq2qP5eCrmRjYc1fj3ER6H5I1e

## Component 4 – EDA_Fixed

Import Libraries
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
sns.set(style="whitegrid")

print("All libraries imported successfully!")

"""Load Dataset (FIXED)"""

file_path = "/content/component4_performance_fixed.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")

"""First Look at Dataset"""

# First 5 rows
df.head()

"""Shape & Columns"""

# Dataset shape
print("Rows and Columns:", df.shape)

# Column names
df.columns

"""Dataset Information"""

df.info()

"""Statistical Summary"""

df.describe()

"""Missing Values"""

# Missing values count
df.isnull().sum()

# Missing values percentage
(df.isnull().mean() * 100).round(2)

"""Separate Column Types"""

numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = df.select_dtypes(include=['object']).columns

print("Numerical Columns:\n", numerical_cols)
print("\nCategorical Columns:\n", categorical_cols)

"""# EXPLORATORY DATA ANALYSIS (EDA)

Waiting Time Histogram
"""

plt.figure(figsize=(8,5))
sns.histplot(df['waiting_time'], bins=30, kde=True)
plt.title("Waiting Time Distribution")
plt.xlabel("Waiting Time")
plt.ylabel("Frequency")
plt.show()

"""Speed Histogram"""

plt.figure(figsize=(8,5))
sns.histplot(df['average_speed'], bins=30, kde=True)
plt.title("Average Speed Distribution")
plt.xlabel("Average Speed")
plt.ylabel("Frequency")
plt.show()

"""Waiting Time Boxplot"""

plt.figure(figsize=(6,4))
sns.boxplot(x=df['waiting_time'])
plt.title("Waiting Time Boxplot")
plt.show()

"""Speed Boxplot"""

plt.figure(figsize=(6,4))
sns.boxplot(x=df['average_speed'])
plt.title("Boxplot of Average Speed")
plt.xlabel("Average Speed")
plt.show()

"""Histograms for All Numerical Columns"""

df[numerical_cols].hist(figsize=(14,10), bins=25)
plt.suptitle("Histograms of Numerical Features", fontsize=16)
plt.show()

"""Boxplots for All Numerical Columns"""

plt.figure(figsize=(14,6))
sns.boxplot(data=df[numerical_cols])
plt.xticks(rotation=90)
plt.title("Boxplots of Numerical Features")
plt.show()

"""Correlation Heatmap"""

plt.figure(figsize=(10,8))
sns.heatmap(df[numerical_cols].corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()