# -*- coding: utf-8 -*-
"""Component 4 – Data Preprocessing (Fixed-Time Dataset).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCuVH_os3U0yqNjTmjOXWuA_nxSytwbH
"""

import pandas as pd
import numpy as np

df = pd.read_csv("component4_cleaned_dataset.csv")
df.head()

df.info()

X = df.drop("delay_ratio", axis=1)
y = df["delay_ratio"]

X = X.drop("vehicle_id", axis=1)

X = pd.get_dummies(X, drop_first=True)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

X_scaled.head()
print("Final feature shape:", X_scaled.shape)

X_scaled.to_csv("component4_preprocessed_features.csv", index=False)
y.to_csv("component4_target.csv", index=False)

