# -*- coding: utf-8 -*-
"""Component4_adaptive_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TGmZE7TMLUGd7IB5f5h94hYGenT97Omz

## Import Required Libraries
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
sns.set(style="whitegrid")

"""##Load the Dataset"""

# Load adaptive dataset
df = pd.read_csv("/content/component4_performance_adaptive.csv")

# Preview data
df.head()

"""##Dataset Shape & Basic Info"""

# Shape of dataset
print("Rows & Columns:", df.shape)

# Dataset information
df.info()

"""##Column Names"""

df.columns

"""##Column Names"""

df.describe()

"""##Check Missing Values"""

df.isnull().sum()

(df.isnull().sum() / len(df)) * 100

"""##Check Duplicate Rows"""

df.duplicated().sum()

"""##Data Types Check"""

df.dtypes

"""##Unique Values per Column"""

df.nunique()

"""##Target Variable Distribution"""

target_col = df.columns[-1]  # assuming last column is target
df[target_col].value_counts()

plt.figure(figsize=(6,4))
sns.countplot(x=target_col, data=df)
plt.title("Target Variable Distribution")
plt.show()

"""##Numerical Feature Distribution"""

num_cols = df.select_dtypes(include=['int64', 'float64']).columns

df[num_cols].hist(figsize=(15,10), bins=20)
plt.suptitle("Numerical Feature Distributions")
plt.show()

"""##Boxplot – Outlier Detection"""

plt.figure(figsize=(15,8))
sns.boxplot(data=df[num_cols])
plt.xticks(rotation=90)
plt.title("Boxplot of Numerical Features")
plt.show()

"""##Categorical Feature Analysis"""

cat_cols = df.select_dtypes(include=['object']).columns

for col in cat_cols:
    plt.figure(figsize=(6,4))
    sns.countplot(y=col, data=df)
    plt.title(f"Distribution of {col}")
    plt.show()

"""##Correlation Matrix"""

plt.figure(figsize=(12,8))
corr = df[num_cols].corr()

sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

"""##Feature vs Target Relationship"""

for col in num_cols:
    if col != target_col:
        plt.figure(figsize=(5,3))
        sns.boxplot(x=target_col, y=col, data=df)
        plt.title(f"{col} vs {target_col}")
        plt.show()

"""##Pair Plot"""

num_cols = df.select_dtypes(include=['float64','int64']).columns

# Pairplot without target
sns.pairplot(df[num_cols])
plt.show()