# -*- coding: utf-8 -*-
"""Component4_Fixed_Modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZlHgPfvyeFFzy_KMjPk_KghEWdYH2rV
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

X = pd.read_csv("component4_preprocessed_features.csv")
y = pd.read_csv("component4_target.csv")

y = y.values.ravel()

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree Regressor": DecisionTreeRegressor(random_state=42),
    "Random Forest Regressor": RandomForestRegressor(random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    results.append([name, mae, mse, r2])

results_df = pd.DataFrame(
    results,
    columns=["Model", "MAE", "MSE", "R2 Score"]
)

results_df.sort_values(by="R2 Score", ascending=False)

best_model = RandomForestRegressor(random_state=42)
best_model.fit(X_train, y_train)

y_pred_best = best_model.predict(X_test)

print("Final Model Performance:")
print("MAE:", mean_absolute_error(y_test, y_pred_best))
print("MSE:", mean_squared_error(y_test, y_pred_best))
print("R2 Score:", r2_score(y_test, y_pred_best))

import joblib

joblib.dump(best_model, "component4_fixed_random_forest_model.pkl")