import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

print("--- INITIALIZING ML SPEED PREDICTOR ---")

# 1. Load the dataset that was just generated by adaptive_equilibrium.py
file_name = "component3_control_adaptive_runtime.csv"
try:
    df = pd.read_csv(file_name)
    print(f"Successfully loaded {file_name}")
except FileNotFoundError:
    print(f"Error: Cannot find {file_name}. Did you run adaptive_equilibrium.py first?")
    exit()

# 2. Filter Data
# We only want to train the AI on moments where there were actually cars on the road.
# If speed is 0.0 and pressure is 0, the road was just empty, which confuses the AI.
df_clean = df[(df['average_speed'] > 0) | (df['junction_pressure'] > 0)]

# 3. Define Features (Inputs) and Target (Output)
features = ['phase_duration', 'green_count', 'junction_pressure', 'average_network_pressure']
target = 'average_speed'

X = df_clean[features]
y = df_clean[target]

# 4. Train/Test Split (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 5. Train the Random Forest Model
print("Training Random Forest Regressor...")
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 6. Make Predictions
y_pred = model.predict(X_test)

# 7. Evaluate Performance
accuracy = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("\n--- MODEL RESULTS ---")
print(f"R² Score (Accuracy): {accuracy:.4f}")
print(f"Mean Absolute Error: {mae:.2f} km/h")

# 8. Visualizing the Prediction Accuracy
plt.figure(figsize=(9, 6))
sns.scatterplot(x=y_test, y=y_pred, alpha=0.5, color='dodgerblue')
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', lw=2, label='Perfect Prediction')
plt.title('Vehicle Speed Prediction: Actual vs. AI Predicted')
plt.xlabel('Actual Average Speed (km/h)')
plt.ylabel('Predicted Average Speed (km/h)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

# 9. Visualizing Feature Importance (What affects speed the most?)
importances = model.feature_importances_
plt.figure(figsize=(8, 4))
sns.barplot(x=importances, y=features, palette='viridis')
plt.title('What factors impact vehicle speed the most?')
plt.xlabel('Importance Score')
plt.ylabel('Traffic Features')
plt.tight_layout()
plt.show()